Repository WordPress/abilities-api, pull requests merged in 2025-09, with the labels that each got.

#54 dev!: handle property registration inside WP_Ability
  includes/abilities-api/class-wp-abilities-registry.php
  includes/abilities-api/class-wp-ability.php
  tests/unit/abilities-api/wpAbilitiesRegistry.php
Labels: [Type] Enhancement

#81 fix: use link_header instead of add_link for pagination responses
  includes/rest-api/endpoints/class-wp-rest-abilities-list-controller.php
  tests/unit/rest-api/wpRestAbilitiesListController.php
Labels: [Type] Bug

#70 Add client library tests and code quality infrastructure
  .github/workflows/test.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
  packages/client/.gitignore
  packages/client/.prettierignore
  packages/client/README.md
  packages/client/jest.config.js
  packages/client/package-lock.json
  packages/client/package.json
  packages/client/src/__tests__/api.test.ts
  packages/client/src/__tests__/validation.test.ts
  packages/client/src/api.ts
  packages/client/src/store/__tests__/actions.test.ts
  packages/client/src/store/__tests__/resolvers.test.ts
  packages/client/src/store/__tests__/selectors.test.ts
  packages/client/src/store/actions.ts
  packages/client/src/store/index.ts
  packages/client/src/validation.ts
  packages/client/tsconfig.json
Labels: [Type] Enhancement

#74 dev: add `register_ability_args` filter [Proposal]
  docs/6.hooks.md
  includes/abilities-api/class-wp-abilities-registry.php
  tests/unit/abilities-api/wpAbilitiesRegistry.php
Labels: [Type] Enhancement

#96 Docs/semantic headings
  docs/1.intro.md
  docs/3.registering-abilities.md
  docs/4.using-abilities.md
Labels: [Type] Developer Documentation
