Repository WordPress/abilities-api, pull requests merged in 2025-08, with the labels that each got.

#3 Implement server-side registry for Abilities API
  .editorconfig
  phpunit.xml.dist
  src/abilities-api.php
  src/class-wp-abilities-registry.php
  src/class-wp-ability.php
  tests/bootstrap.php
  tests/unit/AbilitiesAPITest.php
  tests/unit/WPAbilitiesRegistryTest.php
Labels: [Status] In Progress, [Type] Task

#4 chore: scaffold plugin entrypoint and tooling
  .editorconfig
  .github/workflows/copilot-setup-steps.yml
  .github/workflows/test.yml
  .gitignore
  .nvmrc
  .prettierignore
  .prettierrc.js
  .wordpress-org/.gitkeep
  .wp-env.json
  CONTRIBUTING.md
  README.md
  abilities-api.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  tests/_output/.gitkeep
  tests/bootstrap.php
Labels: [Type] Task

#19 dev: use `WP_Abilities_Registry::$instance` instead of adding a new `global`
  includes/abilities-api/class-wp-abilities-registry.php
  tests/unit/abilities-api/wpRegisterAbility.php
Labels: [Type] Enhancement

#23 dev!: return `WP_Error` from `WP_Ability` methods
  includes/abilities-api/class-wp-ability.php
  includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php
  tests/unit/abilities-api/wpRegisterAbility.php
  tests/unit/rest-api/wpRestAbilitiesRunController.php
Labels: [Type] Enhancement

#10 Adding initial developer documentation
  docs/1.intro.md
  docs/2.getting-started.md
  docs/3.registering-abilities.md
  docs/4.using-abilities.md
Labels: [Type] Developer Documentation

#27 Update readme with links to documenation
  README.md
Labels: [Type] Developer Documentation

#29 Add LICENSE.md file
  .gitignore
  LICENSE.md
  README.md
  abilities-api.php
  package.json
Labels: [Tool]

#31 Refactor error handling in REST API run controller
  includes/abilities-api/class-wp-ability.php
  includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php
  tests/unit/abilities-api/wpRegisterAbility.php
  tests/unit/rest-api/wpRestAbilitiesRunController.php
Labels: [Type] Enhancement

#43 Update an example in Introduction & Overview document
  docs/1.intro.md
Labels: [Type] Developer Documentation

#21 dev!: require `string $name` for registration
  includes/abilities-api.php
  includes/abilities-api/class-wp-abilities-registry.php
  includes/abilities-api/class-wp-ability.php
  tests/unit/abilities-api/wpAbilitiesRegistry.php
  tests/unit/abilities-api/wpRegisterAbility.php
Labels: [Type] Enhancement

#47 Add code quality improvements to code comments
  includes/abilities-api.php
  includes/abilities-api/class-wp-abilities-registry.php
  includes/abilities-api/class-wp-ability.php
  phpcs.xml.dist
  tests/bootstrap.php
  tests/unit/abilities-api/wpAbilitiesRegistry.php
  tests/unit/abilities-api/wpRegisterAbility.php
  tests/unit/rest-api/wpRestAbilitiesListController.php
  tests/unit/rest-api/wpRestAbilitiesRunController.php
Labels: Good First Review

#35 Chore: Configure the composer package for publishing
  .gitattributes
  .wordpress-org/.gitkeep
  abilities-api.php
  composer.json
  composer.lock
  includes/abilities-api.php
  includes/bootstrap.php
  includes/rest-api/class-wp-rest-abilities-init.php
  includes/rest-api/endpoints/class-wp-rest-abilities-list-controller.php
  includes/rest-api/endpoints/class-wp-rest-abilities-run-controller.php
Labels: [Tool]

#33 Documentation: Include specific nvm version needed
  CONTRIBUTING.md
Labels: [Type] Developer Documentation
